import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Image from 'next/image'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const circleSizes = [
    'size-[1340px]',
    'size-[1040px]',
    'size-[740px]',
    'size-[540px]',
    'size-[340px]',
    'size-[140px]',
  ]
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <div className="absolute inset-0 flex items-center justify-center z-0">
          {circleSizes.map((size, i) => (
            <div
              key={i}
              className={` ${size}  rounded-full border border-gray-300/50 absolute z-50`}
            />
          ))}
          <div className="w-[50px] h-[50px] ml-[50px] absolute mb-[200px] bg-[#F3F4F6] z-110" />
          <div className="w-[60px] h-[60px] ml-[60px] absolute mb-[199px] rounded-bl-[85%] bg-[#122249] z-110" />

          <div className="w-[50px] h-[50px] ml-[50px] absolute mt-[200px] bg-[#F3F4F6] z-110" />
          <div className="w-[60px] h-[60px] ml-[60px] absolute mt-[199px] rounded-tl-[85%] bg-[#122249] z-110" />

          <div className="w-[80px] h-[80px] ml-[80px] absolute mb-[80px] rounded-tr-[100%] bg-[#F3F4F6] z-100" />
          <div className="w-[80px] h-[80px] ml-[80px] absolute mt-[80px] rounded-br-[100%] bg-[#F3F4F6] z-100" />

          <Image
            src="/PineconeLogoLeft.png"
            width={43}
            height={86}
            alt="left"
            className="absolute mr-[43px]"
          />
          <Image
            src="/PineconeLogoRight.png"
            width={43}
            height={86}
            alt="right"
            className="absolute ml-[53px] z-111"
          />

          <Image
            src="/orange.png"
            width={128}
            height={128}
            alt="orange"
            className="absolute mr-[1030px] mb-[650px] z-1"
          />
          <Image
            src="/blue.png"
            width={128}
            height={128}
            alt="blue"
            className="absolute ml-[1030px] mt-[650px] z-1"
          />
        </div>
      </body>
    </html>
  )
}
